apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crm-fte
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - kafka.yaml
  - api.yaml
  - worker.yaml
  - web-form.yaml
